### ISSUE TITLE
Any() fails when compared to classes that override __eq__

### ISSUE THREAD

**Issue by jlevitt** [man-group/mockextras#13]
Test case:

```
class Model(object):
    def __init__(self, id):
        self.id = id

    def __eq__(self, other):
        return self.id == other.id


def test_any():
    service = Mock()
    when(service.do_a_thing)\
        .called_with(Any())\
        .then(True)

    # Should pass, but instead gives `AttributeError: 'Any' object has no attribute 'id'`
    assert service.do_a_thing(Model(1))
```

**Comment by burrowsa** [comment]
Hi

The problem lies in your implementation of `__eq__` I'm riffraff. The way that operator overloading works in python for operators that take two arguments (binary operators) is that the relevant special method (aka magic method or dunder method) is called on one of the objects, if that object doesn't now how to do the operation for the supplied operands it signals this by returning `NotImplemented` so the corresponding method is then called on the other object.

More details about this can be found at:

https://docs.python.org/3/reference/datamodel.html#the-standard-type-hierarchy

and

https://docs.python.org/3/library/numbers.html#implementing-the-arithmetic-operations

In your example `__eq__` is being called on an instance of `Model` passing in an instance of `Any` as the other object. Your code doesn't know how to handle this situation and doesn't return `NotImplemented` so the `__eq__` on `Any` never gets a chance to have a go.

It is normal for implementations of operators such as `__eq__` to test the type of the other operand to check whether the operation is implemented. So in your example you should implement the `Model` class as follows:

    class Model(object):
        def __init__(self, id):
            self.id = id

        def __eq__(self, other):
            if isinstance(other, Model):
                return self.id == other.id`
            else:
                return NotImplemented

I hope this helps

**Comment by jlevitt** [comment]
Thanks for the in-depth explanation. I thought it may have to do with the order in which the arguments are passed to `==`, but this makes more sense!
